# @package _global_
adapter_config:
  name: TSA_LAME
  iter_epochs: 1
  scale_epochs: 1
  scale_lr: 0.001
  scale_thre: 0.1
  pa_ratio: 0.01
  cal_type: predict_target
  base_tta: LAME
  epochs: 50
  kNN: 5
  kernel: kNN
  sigma: 1