# @package _global_
adapter_config:
  name: TSA_TENT
  iter_epochs: 1
  scale_epochs: 1
  scale_lr: 0.001
  scale_thre: 0.1
  pa_ratio: 0.01
  cal_type: predict_target
  base_tta: TENT
  bn_feature: ${model_config.bn_feature}
  bn_classifier: ${model_config.bn_classifier}
  epochs: 1
  lr: 0.001